### PR TITLE
Added the optional locale scope to the config/routes.rb file. Added a…

### PR DESCRIPTION
**Pull request by briri**
… configuration variable called localize_routes that users can enable (disabled by default). This should prevent conflicts with any installations using a parent path that is not a locale (e.g. /blog/contact-us). Also updated the README to inform the users about the new option and incremented the version number.

### CODE REVIEW

**Comment by briri** [comment]
I don't think the Travis failures are due to these changes.

**Comment by JDutil** [comment]
@briri awesome I've made some updates to fix the broken build.  Could you please update to the latest master to get the fixes, you can remove the version bump that I'll handle, and cleanup the extra/trailing whitespace warnings. Thank you.

**Comment by briri** [comment]
All set JDutil. I rebased and cleaned up the remaining houndci warnings. I also removed the version number change I had made. Thanks!

**Comment by JDutil** [comment]
Thanks @briri I've release version 1.2.0 with this included.

**Pull request merged**
